---
type: yml
auth:
  sign_key: jwt_secret

http_server:
  port: 8088

mysql:
  port: 3306
  host: localhost
  db_name: gameapp_db
  username: gameapp
  password: gameapp

redis:
  port: 6380
  host: localhost
  db: 0
  password: ""

matching_service:
  waiting_timeout: "2m"